/* global React */
// Sample data — fake products, posts, clicks, etc.

const PRODUCTS = [
  {
    id: 'P-2841',
    title: 'Magnetic Cable Organizer (6-pack, silicone)',
    price: '$4.97',
    margin: '$1.42',
    discovered: '2026-04-22',
    status: 'live',
    score: 94,
    flagged: true,
    clicks: 1284,
    earnings: 38.21,
    posts: 9,
    angles: 15,
    img: 'cable-organizer',
    note: 'Top performer — Pinterest carrying it',
  },
  {
    id: 'P-2840',
    title: 'Foldable Travel Hairdryer 1200W',
    price: '$12.49',
    margin: '$3.50',
    discovered: '2026-04-21',
    status: 'live',
    score: 88,
    clicks: 612,
    earnings: 18.20,
    posts: 6,
    angles: 12,
    img: 'hairdryer',
  },
  {
    id: 'P-2839',
    title: 'LED Strip Lights, RGB, 32ft, app-controlled',
    price: '$8.99',
    margin: '$2.10',
    discovered: '2026-04-21',
    status: 'queued',
    score: 76,
    clicks: 0,
    earnings: 0,
    posts: 0,
    angles: 15,
    img: 'led-strip',
  },
  {
    id: 'P-2838',
    title: 'Stainless Steel Garlic Press',
    price: '$3.29',
    margin: '$0.94',
    discovered: '2026-04-20',
    status: 'scheduled',
    score: 71,
    clicks: 84,
    earnings: 2.80,
    posts: 3,
    angles: 12,
    img: 'garlic-press',
  },
  {
    id: 'P-2837',
    title: 'Self-Stirring Mug, USB rechargeable',
    price: '$6.79',
    margin: '$1.85',
    discovered: '2026-04-19',
    status: 'live',
    score: 82,
    clicks: 491,
    earnings: 14.10,
    posts: 5,
    angles: 12,
    img: 'mug',
  },
  {
    id: 'P-2836',
    title: 'Mini Portable Bluetooth Speaker, 5W',
    price: '$9.49',
    margin: '$2.40',
    discovered: '2026-04-18',
    status: 'live',
    score: 79,
    clicks: 308,
    earnings: 9.60,
    posts: 4,
    angles: 12,
    img: 'speaker',
  },
  {
    id: 'P-2835',
    title: 'Adjustable Laptop Stand, aluminum, foldable',
    price: '$14.99',
    margin: '$4.20',
    discovered: '2026-04-17',
    status: 'live',
    score: 90,
    flagged: true,
    clicks: 887,
    earnings: 31.42,
    posts: 7,
    angles: 15,
    img: 'laptop-stand',
  },
  {
    id: 'P-2834',
    title: 'Pet Hair Remover Roller, reusable',
    price: '$5.49',
    margin: '$1.50',
    discovered: '2026-04-16',
    status: 'paused',
    score: 64,
    clicks: 142,
    earnings: 4.50,
    posts: 4,
    angles: 12,
    img: 'pet-roller',
    note: 'Low CTR on Pinterest, paused',
  },
  {
    id: 'P-2833',
    title: 'Silicone Stretch Lids (12-pack)',
    price: '$4.19',
    margin: '$1.10',
    discovered: '2026-04-15',
    status: 'live',
    score: 85,
    clicks: 521,
    earnings: 14.80,
    posts: 6,
    angles: 12,
    img: 'lids',
  },
  {
    id: 'P-2832',
    title: 'Wireless Earbuds, Bluetooth 5.3',
    price: '$11.99',
    margin: '$3.10',
    discovered: '2026-04-14',
    status: 'live',
    score: 81,
    clicks: 405,
    earnings: 12.40,
    posts: 5,
    angles: 12,
    img: 'earbuds',
  },
  {
    id: 'P-2831',
    title: 'Reusable Cotton Rounds (16-pack, washable)',
    price: '$3.79',
    margin: '$0.90',
    discovered: '2026-04-13',
    status: 'live',
    score: 73,
    clicks: 198,
    earnings: 5.80,
    posts: 4,
    angles: 12,
    img: 'cotton-rounds',
  },
  {
    id: 'P-2830',
    title: 'Car Phone Holder, vent mount, magnetic',
    price: '$5.99',
    margin: '$1.60',
    discovered: '2026-04-12',
    status: 'live',
    score: 77,
    clicks: 264,
    earnings: 7.90,
    posts: 5,
    angles: 12,
    img: 'phone-holder',
  },
];

const TONES = [
  { id: 'practical', label: 'Practical', desc: 'Plainspoken. Use-case first. The "this just works" angle.', char: 'P' },
  { id: 'premium', label: 'Premium', desc: 'Aspirational. Lifestyle. The "you deserve it" angle.', char: 'M' },
  { id: 'witty', label: 'Witty', desc: 'Punchy. Conversational. The "stop scrolling" angle.', char: 'W' },
];

// Angle copy keyed by [productId]?[platform][toneId] — for our hero product
const ANGLES = {
  // Cable organizer
  tg: {
    practical: {
      copy: "Six magnetic cable holders. Stick them on the back of your desk, your nightstand, the side of your monitor — wherever cables go to die. Each one snaps shut around the cable so it doesn't slip out when you reach for it.\n\n→ Charging cable, headphone cable, USB-C, all of it. Reusable adhesive, takes thirty seconds to install.\n\n$4.97 • free shipping",
      cta: 'Get the 6-pack',
      hashtags: '',
    },
    premium: {
      copy: "Your desk deserves better than a tangled drawer of charging cables.\n\nThis 6-pack of magnetic silicone holders gives every cable a home — clean lines, no clutter, ready when you need them.\n\nA small upgrade that makes the rest of your setup feel intentional.",
      cta: 'Tidy your space',
      hashtags: '',
    },
    witty: {
      copy: "POV: you finally figured out where your charger went.\n\n6 magnetic clips. Stick 'em anywhere. Cables stay put. The end.\n\nNo more 4am phone-light cable hunts. You're welcome.\n\n$4.97 → link below ↓",
      cta: 'Save me from cable jail',
      hashtags: '',
    },
  },
  pin: {
    practical: {
      copy: "Magnetic cable organizers — 6-pack for under $5. Reusable adhesive, fits any cable size, hides behind the desk so you don't see them.",
      title: '6 cable holders that actually stay stuck',
      cta: 'Shop the 6-pack',
      hashtags: '#cablemanagement #deskorganization #homeoffice #organize',
    },
    premium: {
      copy: "The desk setup detail you didn't know you needed. Magnetic silicone cable keepers — clean, hidden, reusable.",
      title: 'Desk organization done right',
      cta: 'See the set',
      hashtags: '#deskaesthetic #minimalsetup #wfhideas #cleanspaces',
    },
    witty: {
      copy: "Cables disappearing under your desk? Same. These magnetic clips fix that for $4.97.",
      title: 'Where do cables go when they die?',
      cta: 'Catch them all',
      hashtags: '#lifehack #organizationhack #amazonfinds #temufinds',
    },
  },
  x: {
    practical: {
      copy: "6 magnetic cable holders for $4.97.\n\nStick them anywhere, cables snap in place, reusable adhesive. That's it, that's the post.",
      cta: 'Link',
      hashtags: '',
    },
    premium: {
      copy: "Subtle desk upgrade I keep recommending: magnetic silicone cable keepers. 6-pack, under $5, makes everything look intentional.",
      cta: 'Get them',
      hashtags: '',
    },
    witty: {
      copy: "me: i need to declutter my desk\nalso me: spends 4 hours googling cable management\n\nfound the answer. it's $4.97. moving on with my life.",
      cta: '↓',
      hashtags: '',
    },
  },
  tt: {
    practical: {
      copy: "[Hook 0-3s] Show the cable mess.\n[Beat 3-8s] Apply one clip behind the monitor, snap a cable in.\n[Beat 8-15s] Repeat with all six. Time-lapse.\n[Outro 15-20s] Final clean shot. Voiceover: '6 of these for $4.97. Link in bio.'",
      cta: 'Script + assets ready',
      hashtags: '#temufinds #organizationtips #deskmakeover',
    },
    premium: { copy: '[Premium variant — generated]', cta: '', hashtags: '' },
    witty: { copy: '[Witty variant — generated]', cta: '', hashtags: '' },
  },
  ig: {
    practical: {
      copy: "Cable organization, finally solved. 6 magnetic holders, $4.97. Link in bio.",
      cta: 'Link in bio',
      hashtags: '#temufinds #organization #deskhacks',
    },
    premium: { copy: '[Premium variant]', cta: '', hashtags: '' },
    witty: { copy: '[Witty variant]', cta: '', hashtags: '' },
  },
};

// Scheduled posts (for calendar / queue)
const POSTS = [
  { id: 'PST-9821', product: 'Magnetic Cable Organizer', platform: 'pin', tone: 'practical', when: 'Today, 09:00', status: 'live', clicks: 142, earnings: 4.20 },
  { id: 'PST-9822', product: 'Magnetic Cable Organizer', platform: 'tg', tone: 'witty', when: 'Today, 10:30', status: 'live', clicks: 318, earnings: 9.80, hot: true },
  { id: 'PST-9823', product: 'Adjustable Laptop Stand', platform: 'pin', tone: 'premium', when: 'Today, 11:00', status: 'live', clicks: 89, earnings: 3.10 },
  { id: 'PST-9824', product: 'Foldable Travel Hairdryer', platform: 'x', tone: 'witty', when: 'Today, 13:00', status: 'scheduled', clicks: 0, earnings: 0 },
  { id: 'PST-9825', product: 'LED Strip Lights', platform: 'pin', tone: 'practical', when: 'Today, 15:00', status: 'scheduled', clicks: 0, earnings: 0 },
  { id: 'PST-9826', product: 'Self-Stirring Mug', platform: 'tg', tone: 'witty', when: 'Today, 17:30', status: 'scheduled', clicks: 0, earnings: 0 },
  { id: 'PST-9827', product: 'Magnetic Cable Organizer', platform: 'x', tone: 'practical', when: 'Today, 19:00', status: 'scheduled', clicks: 0, earnings: 0 },
];

// Live click feed
const FEED = [
  { t: '11:42:18', product: 'Magnetic Cable Organizer', platform: 'pin', tone: 'practical', country: 'US', earned: 0.31 },
  { t: '11:41:55', product: 'Adjustable Laptop Stand', platform: 'tg', tone: 'witty', country: 'CA', earned: 0.42 },
  { t: '11:41:12', product: 'Magnetic Cable Organizer', platform: 'pin', tone: 'practical', country: 'UK', earned: 0.28 },
  { t: '11:40:47', product: 'Self-Stirring Mug', platform: 'tg', tone: 'witty', country: 'US', earned: 0.18 },
  { t: '11:40:20', product: 'Foldable Travel Hairdryer', platform: 'x', tone: 'practical', country: 'AU', earned: 0.35 },
  { t: '11:39:58', product: 'Magnetic Cable Organizer', platform: 'tg', tone: 'witty', country: 'US', earned: 0.31, click: true },
  { t: '11:39:14', product: 'Silicone Stretch Lids', platform: 'pin', tone: 'practical', country: 'US', earned: 0.22 },
];

const KPIS = {
  earningsMtd: 1284.42,
  earningsDelta: '+18.4%',
  earningsSpark: [820, 870, 910, 940, 1010, 1040, 1090, 1140, 1190, 1240, 1284],
  clicksToday: 1842,
  clicksDelta: '+24.1%',
  clicksSpark: [120, 180, 90, 200, 240, 170, 280, 320, 290, 340, 380],
  ctr: 4.82,
  ctrDelta: '+0.31',
  ctrSpark: [3.8, 4.0, 4.1, 4.2, 4.3, 4.4, 4.4, 4.5, 4.6, 4.7, 4.82],
  posted: 47,
  postedDelta: '+12',
  postedSpark: [2, 3, 5, 4, 6, 5, 7, 8, 6, 7, 4],
};

window.ALFI_DATA = { PRODUCTS, TONES, ANGLES, POSTS, FEED, KPIS };
